default_install_hook_types:
  - pre-commit
  - post-checkout
  - post-merge
  - post-rewrite
default_language_version:
    python: python3.13

repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.9
    hooks:
      - id: uv-sync
        args: [ --project=backend]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
        exclude: (?x)(^frontend/|^resources/)
        stages: [pre-commit]
      - id: ruff-format
        stages: [pre-commit]
        exclude: (?x)(^frontend/|^resources/)

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright
        files: ^backend/
        args: [ --project=backend ]