name: Backed CI workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  backend_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          working-directory: ./backend
      - name: Install dependencies
        run: uv sync --group ci --no-group dev
        working-directory: ./backend
      - name: Run linting
        run: uv run ruff check
        working-directory: ./backend
      - name: Run type checking
        run: uv run pyright
        working-directory: ./backend